build: false
clone_folder: c:\project

platform:
    - x86
    - x64

branches:
    only:
        - master

cache:
    - c:\php -> appveyor.yml
    - c:\selenium -> appveyor.yml

init:
    - SET PATH=c:\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET PHP=1
    - SET SELENIUM=1

install:
    - IF EXIST c:\php (SET PHP=0) ELSE (mkdir c:\php)
    - cd c:\php
    - IF %PHP%==1 appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-7.1.0-nts-Win32-VC14-%platform%.zip
    - IF %PHP%==1 7z x php-7.1.0-nts-Win32-VC14-%platform%.zip -y >nul
    - IF %PHP%==1 del /Q *.zip
    - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
    - IF %PHP%==1 copy /Y php.ini-development php.ini
    - IF %PHP%==1 echo memory_limit=256M >> php.ini
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_curl.dll >> php.ini
    - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - IF EXIST c:\selenium (SET SELENIUM=0) ELSE (mkdir c:\selenium)
    - cd c:\selenium
    - IF %SELENIUM%==1 appveyor DownloadFile https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar
    - IF %SELENIUM%==1 appveyor DownloadFile https://chromedriver.storage.googleapis.com/2.27/chromedriver_win32.zip
    - IF %SELENIUM%==1 7z x chromedriver_win32.zip -y >nul
    - IF %SELENIUM%==1 del /Q *.zip
    - ps: Start-Process java -ArgumentList '-jar selenium-server-standalone-2.53.0.jar -Dwebdriver.chrome.driver=chromedriver.exe'
    - cd c:\project
    - composer update --prefer-source

test_script:
    - cd c:\project
    - vendor\bin\phpunit.bat --configuration phpunit.ci.xml
